services:
   consul:
        image: consul:latest
        command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
        hostname: consul
        container_name: consul
        networks:
            - common_network
   redis:
        image: redis:6.2-alpine
        command: redis-server --save 20 1 --loglevel warning
        hostname: redis
        container_name: redis
        networks:
            - common_network

   chatsessionservice1:
        container_name: chatsessionservice1
        image: chatsessionservice:latest
        restart: on-failure
        hostname: chatsessionservice1
        build:
            context: .
            dockerfile: ChatSessionService/Dockerfile
        networks:
            - common_network
                   
   messagedistributionservice:
        container_name: messagedistributionservice
        image: messagedistributionservice:latest
        restart: on-failure
        hostname: messagedistributionservice
        build:
            context: .
            dockerfile: MessageDistributionService/Dockerfile
        networks:
            - common_network