services:
   consul:
        image: consul:latest
        command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
        hostname: consul
        container_name: consul
        networks:
            - common_network
   redis:
        container_name: redisacl
        image: redisacl:latest
        hostname: redisacl
        build:
            context: .
            dockerfile: Redis/Dockerfile
        networks:
            - common_network

   chatsessionservice1:
        container_name: chatsessionservice1
        image: chatsessionservice:latest
        restart: on-failure
        hostname: chatsessionservice1
        build:
            context: .
            dockerfile: ChatSessionService/Dockerfile
        networks:
            - common_network

   usersservice:
        container_name: usersservice
        image: usersservice:latest
        restart: on-failure
        hostname: usersservice
        build:
            context: .
            dockerfile: Users/Dockerfile
        networks:
            - common_network      

   gateway:
        container_name: gateway
        image: gateway:latest
        restart: on-failure
        hostname: gateway
        build:
            context: .
            dockerfile: Gateway/Dockerfile
        networks:
            - common_network

   mysql:
        container_name: mysql_server
        image: mysql:5.7
        restart: on-failure
        hostname: mysql_server
        networks:
            - common_network