services:
   consul:
        image: consul:latest
        command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
        hostname: consul
        container_name: consul
        networks:
            - common_network
   redis:
        container_name: redisacl
        image: redisacl:latest
        hostname: redisacl
        build:
            context: .
            dockerfile: Redis/Dockerfile
        networks:
            - common_network

   chatsessionservice1:
        container_name: chatsessionservice1
        image: chatsessionservice:latest
        restart: on-failure
        hostname: chatsessionservice1
        build:
            context: .
            dockerfile: ChatSessionService/Dockerfile
        networks:
            - common_network
