services:
    consul:
        ports:
             - "8500:8500"
    redis:
        ports:
             - "6379:6379"

    chatsessionservice1:
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ServiceConfig__Id=ChatSessionService-9100
          - ServiceConfig__Name=ChatSessionService
          - ServiceConfig__DiscoveryAddress=http://consul:8500
          - ServiceConfig__RedisHostname=redis
          - ServiceConfig__RedisInstanceName=Cache
          - ServiceConfig__Address=chatsessionservice1
          - ServiceConfig__Port=80
        ports:
            - 9100:80
        depends_on:
            - consul

networks:
    common_network:
        driver: bridge